name: Deploy to NAS Server

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  SERVER_DOCKER_IMG_NAME: h-domi-blog # 여기에 실제 이미지 이름을 입력하세요
  SERVER_NAME: domi-blog # 여기에 실제 서버 이름을 입력하세요

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secrets에 SSH 키를 저장하세요

      - name: Build and Deploy Docker Image
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.NAS_USER }}@${{ secrets.NAS_IP }} -p ${{ secrets.NAS_PORT }} << 'EOF'
            cd /volume1/docker/frontend
            rm -rf ${{ env.SERVER_NAME }}
            mkdir ${{ env.SERVER_NAME }}
            git clone -b main --single-branch https://github.com/HDomi/domi-blog.git
            cd ${{ env.SERVER_NAME }}
            docker stop ${{ env.SERVER_DOCKER_IMG_NAME }} || true
            docker rm ${{ env.SERVER_DOCKER_IMG_NAME }} || true
            sleep 30
            docker build --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} --build-arg NEXT_PUBLIC_SUPABASE_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }} --build-arg NEXT_PUBLIC_USER_ID=${{ secrets.NEXT_PUBLIC_USER_ID }} -t ${{ env.SERVER_DOCKER_IMG_NAME }}:latest -f Dockerfile . && \
            docker run -e NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} -e NEXT_PUBLIC_SUPABASE_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }} -e NEXT_PUBLIC_USER_ID=${{ secrets.NEXT_PUBLIC_USER_ID }} -d --name ${{ env.SERVER_DOCKER_IMG_NAME }} -p 3000:3000 ${{ env.SERVER_DOCKER_IMG_NAME }}:latest
          EOF
